# Generated by Django 5.1.4 on 2024-12-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('etat', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé')], default='EN_ATTENTE', max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
