# Generated by Django 5.1.4 on 2025-01-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='etat',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
