# Generated by Django 5.2.1 on 2025-08-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
    ]
